# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    xmlparser:
        class: AppBundle\Services\XMLParser
        arguments: ['@doctrine.orm.entity_manager']