app:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }
    methods:  GET

app_organizations:
    resource: "@AppBundle/Resources/config/routing/organizations.yml"
    prefix:   /organizations

app_users:
    resource: "@AppBundle/Resources/config/routing/users.yml"
    prefix:   /users
app_import:
    path:     /xml
    defaults: { _controller: AppBundle:XMLParser:index }
